### ISSUE TITLE
Make C code and R code produce the same results

### ISSUE THREAD

**Issue by jnpaulson** [QuackenbushLab/pandaR#12]
@ayoung01

Ensure the C code and R code produce the same output. Additionally, produce C output and put it in a unit test for the `panda` function (similar to what's here: https://github.com/HCBravoLab/metagenomeSeq/tree/master/inst/unitTests)

**Comment by jnpaulson** [comment]
Perfect - I'll just leave this open till we have a test or two. Awesome work so far :)

**Comment by ayoung01** [comment]
Thanks! I'll take care of that soon

**Comment by jnpaulson** [comment]
Update: https://github.com/QuackenbushLab/pandaR/commit/75fe573172cae04cf9fc8e52c3bfbe872b01ae78
