### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by jnpaulson** [QuackenbushLab/pandaR#14]
Create unit tests for `plotZ` and `testMotif`. @ayoung01, do you think you'd have time for that? Awesome work so far by the way!

**Comment by ayoung01** [comment]
thanks! will take care of it

**Comment by ayoung01** [comment]
Do you have suggestions on how I should test the graphical output of functions? I found this thread (http://stackoverflow.com/questions/30246789/how-to-test-graphical-output-of-functions) that recommended the visualTest package (https://github.com/MangoTheCat/visualTest)

**Comment by jnpaulson** [comment]
Too complicated for now:

Try something like this:
https://github.com/joey711/phyloseq/blob/master/tests/testthat/test-plot.R

**Comment by ayoung01** [comment]
Can't figure out what that is testing either.. is it helpful to just test if all the variables are the correct classes? Should I just make sure the intermediate variables aren't NULL?

**Comment by jnpaulson** [comment]
Yeah - you should test if the output of the functions are of the correct 
class, i.e. lists usually if it's a ggplot.

**Comment by ayoung01** [comment]
See #15
