### ISSUE TITLE
Depends in Description

### ISSUE THREAD

**Issue by jnpaulson** [QuackenbushLab/pandaR#3]
Hey Dan,

I was curious if the R >= 3.1.3 was specific to a bug fix in 3.1.3? I can't install the package on another server unless I downgrade the Depends requirement in the DESCRIPTION: https://github.com/dschlauch/pandaR/blob/master/DESCRIPTION#L8. I'd recommend lowering it to whatever is necessary for most users to get access if there isn't a specific 3.1.3 requirement.

**Comment by dschlauch** [comment]
Hey Joe,
There isn't anything specific to 3.1.3 that is required for pandaR, but Bioconductor wanted that dependency and asked that I put it in there.  I believe new packages are asked to require the latest version of R which is available at the time of the first BioC release. 
If you change it and build from source, it should be no problem running on an older version of R.
