### ISSUE TITLE
Improve plotZbyTF

### ISSUE THREAD

**Issue by jnpaulson** [QuackenbushLab/pandaR#5]
Remove use of: `attach(chip.seq.counts)` on https://github.com/QuackenbushLab/pandaR/blob/master/R/plotting.R#L163
https://travis-ci.org/QuackenbushLab/pandaR/builds/86710789#L2122
@ayoung01

**Comment by ayoung01** [comment]
done

**Comment by jnpaulson** [comment]
Thanks @ayoung01, unfortunately the change you made breaks the code. 
See https://travis-ci.org/QuackenbushLab/pandaR/builds/86844031. With the next fix, I recommend using `devtools`' `check` function.
