### ISSUE TITLE
Improve testMotif

### ISSUE THREAD

**Issue by jnpaulson** [QuackenbushLab/pandaR#6]
Currently `panda` outputs a regulatory network without matrix column and row names. This is required, especially for `testMotif`. As a workaround for the `testMotif` we're doing:
``` 
  panda.mod <- panda(motif.mod, expr, ppi, ...)
  reg.mod <- slot(panda.mod,"regNet")
  colnames(reg.mod) = colnames(slot(panda.mod,"coregNet"))
  ...
```
@ayoung01

**Comment by ayoung01** [comment]
Should we be changing ```testMotif``` or changing the output of ```panda``` to have matrix column and row names?

**Comment by jnpaulson** [comment]
panda
